// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_polestar_naosdk_api_external.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, DBTBEACONSTATE)
{
    DBTBEACONSTATE_NO_CHANGE,
    DBTBEACONSTATE_FIRST_UNSEEN,
    DBTBEACONSTATE_FIRST_UNKNOWN,
    DBTBEACONSTATE_FIRST_FAR,
    DBTBEACONSTATE_FIRST_NEAR,
};
