// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_polestar_naosdk_api_external.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, DBTPOWERMODE)
{
    /** accurate power mode */
    DBTPOWERMODE_HIGH,
    /** low-power mode */
    DBTPOWERMODE_LOW,
};
